# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file!

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [7]:
# Import pandas using the standard alias
import pandas as pd

In [63]:
# Import the file and print the first 5 rows
range_ = list(range[0:46])
df = pd.read_csv('Data/Zipcode_Demos.csv', skiprows = 47, usecols = range_)

In [64]:
# Print the last 5 rows of df
df.tail()

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,PERCENT CITIZEN STATUS UNKNOWN,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL
5,10006,6,2,0.33,4,0.67,0,0,6,100,...,0,6,100,0,0.0,6,1.0,0,0,6
6,10007,1,0,0.00,1,1.00,0,0,1,100,...,0,1,100,1,1.0,0,0.0,0,0,1
7,10009,2,0,0.00,2,1.00,0,0,2,100,...,0,2,100,0,0.0,2,1.0,0,0,2
8,10010,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0,0.0,0,0.0,0,0,0
9,10011,3,2,0.67,1,0.33,0,0,3,100,...,0,3,100,0,0.0,3,1.0,0,0,3

In [62]:
# What is going on with this data set? Anything unusual?

In [65]:
# Clean up the dataset

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [70]:
# Hint: Here's a useful programming pattern to use
df = pd.read_csv('Data/Yelp_Reviews_corrupt.csv', nrows = 50)
df
#try:
    # Do something
#except Exception as e:
    # Handle your exception e

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0.0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0.0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1.0,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3.0,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0.0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0.0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0.0,pfavA0hr3nyqO61oupj-lA,1.0,This place sucks. The customer service is horr...,2.0,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0.0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0.0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0.0,HkYqGb0Gplmmk-xlHTRBoA,1.0,The score should be negative. Its HORRIBLE. Th...,0.0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0.0,RgqWdZA4xR023iP3T6jVfA,5.0,I went there twice and I am pretty happy with ...,0.0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0.0,51RHs_V_fjuistnuKxNpEg,5.0,Finally! After trying many Mexican restaurants...,0.0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0.0,alI_kRKyEHfdHibYGgtJbw,1.0,I have to write a review on the Fractured Prun...,0.0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0.0,85DRIjwPJOTb4q0qOlBstw,1.0,I wish i could tell you all about the food but...,1.0,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0.0,GbiLIKmQPVCBtdNkTVdVSA,5.0,Wonderful! One of my favorite places. BBQ is e...,0.0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0.0,UaHgsL0xS4UnJ_iKqeOk_w,5.0,The price is about the same as Quizinos. The s...,0.0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0.0,c4zzAD1S6721Fh-acCBy-g,4.0,The food was ok. You get a lot of food for the...,0.0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0.0,TTBwocu2mvqJFJrwmJN0Sw,5.0,The staff were friendly and helpful. The food ...,1.0,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0.0,-CresnnXQSHrQ85Ogm-Pqw,5.0,The staff were very helpful. We painted potter...,0.0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0.0,U04YgYr4PiGUxB46J4xapg,2.0,Limited vegetarian options. Ordered Greek sala...,0.0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0.0,s9cpVj40VR_yl0lXbZQe6w,5.0,I trust my vehicles here. Comparable prices. M...,0.0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0.0,AJ0IglpYAp2D0daOlVGIdg,1.0,This place doesn't even deserve 1 star. Horrib...,18.0,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0.0,5D_MsAJHrMa8QKkpE3g1Sg,5.0,The butter burger was cooked perfectly and jui...,0.0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0.0,5bWN_IN8MQGjJ6_ZIXffDw,5.0,Best location ever! I love love love the manag...,0.0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0.0,RW_mYzHYfdqn6g7xVgIcKg,4.0,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0.0,SLA1YP9doUc8h-6Kd34QmA,1.0,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0.0,qxPiEGIHy5xyVy78avH5Rg,4.0,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0.0,q6ij-nz5d_hvdjuelho1pQ,5.0,Better service and much better prices than the...,0.0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0.0,66FSK2J1uHJqVI1Z8QiFGw,4.0,I love how they have no rice sushi options. Th...,0.0,Yy_iGXxLpL6tYDQoE-6XVg
30,102,aQ222ydz_GSRZV66xNt4kQ,0,2017-04-09,1.0,AxhxGl41DItKjqkzYtr53Q,1.0,2 of my girlfriends recommended this place so ...,NaN,NaN
31,**someone replied to this comment saying to co...,1,Yy_iGXxLpL6tYDQoE-6XVg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,172,1SnYDvrd02FXSXnIgz-9DQ,0,2010-11-17,4.0,8enQ9Fj-sWkWub4AZQUzeQ,1.0,Huge Apple Danishes! Unfortunatley huge doesnt...,NaN,NaN
33,So what does Westmall Donuts have to offer? He...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Do yourself and your wallet a favour and avoid...,0,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,179,YPa8t1631tlRQms0p331ZQ,0,2016-04-10,0.0,vCwlUF30mV7Eg5MCS3N39Q,4.0,What a nice and friendly person that answered ...,1.0,wMttR-7frrO-YzDsIiA4GQ
36,180,eZCE1u_3ORlX8dHSVTjl9w,0,2016-03-10,1.0,GuD3Og1PmJCqXAiWQe1xew,4.0,I have been here 3 1/2 years. The staff is a...,4.0,wMttR-7frrO-YzDsIiA4GQ
37,182,ruWTngdiC68O9la27hvvHw,0,2016-02-24,0.0,Tifm4ETlt4FXiuGwhq__lg,4.0,This place is not just a restaurant has a grea...,1.0,dQzQ4bN0Rnb8M-0LqTl3-g
38,183,7KkgMcbVaetryW1wwpzvvA,0,2016-02-29,0.0,htV6dNmUqaXwCIRt7vfO5A,4.0,It great fast food and get large portions. It ...,0.0,dQzQ4bN0Rnb8M-0LqTl3-g
39,184,bvGdqJ-SeGdIHX-HEabwlg,0,2016-05-29,0.0,AR_IDHl2P4kUVPB_tTsA6w,4.0,I went there a couple week ago. The service wa...,0.0,dQzQ4bN0Rnb8M-0LqTl3-g
40,185,h1Jq1YlqPyD1mGSW0sjRaQ,0,2016-03-07,0.0,JL6B_spdwG_gLMEdh4Z-Mg,1.0,I call them to switch to their service for bot...,0.0,dQzQ4bN0Rnb8M-0LqTl3-g
41,186,9tLCuUmw3Tlco-tKPGkIWQ,1,2016-03-25,0.0,vPA9ZwuatQhnfu6WrG0mpw,5.0,Great fast food restaurant large portions. The...,1.0,dQzQ4bN0Rnb8M-0LqTl3-g
42,188,ICw43H7hrbSuXTjDBmJxbA,1,2016-02-29,0.0,RUoRwBWiYAZ7FhRMg_ibZA,5.0,I was just at their new store on Cheyenne on S...,1.0,dQzQ4bN0Rnb8M-0LqTl3-g
43,189,_pBXtjN43eqMV0XZTz7nmw,0,2016-03-25,0.0,ohzlH9CWRuP8TehyfTUp6g,4.0,Its a nice club open air with swimming pools t...,0.0,dQzQ4bN0Rnb8M-0LqTl3-g
44,190,3kdSl5mo9dWC4clrQjEDGg,0,2015-10-17,1.0,Bay72mIfR-yGKZf_S9xQeg,4.0,????????????????????????????????????,NaN,NaN
45,?????7:30???,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,?????????????,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,?????????????????,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,??????????????????!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2????????????????????,0,5oy_MM1skY1LvmdNNVVM5Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Summary

Congratulations, you now practiced your Pandas-importing skills!